//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Permission
    {
        public int ActionId { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual APMT_Action APMT_Action { get; set; }
        public virtual APMT_ProductAdmin APMT_ProductAdmin { get; set; }
    }
}
