//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Process()
        {
            this.APMT_Activity = new HashSet<APMT_Activity>();
            this.APMT_Process_Role = new HashSet<APMT_Process_Role>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string JsonContent { get; set; }
        public string Description { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public Nullable<bool> Allowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Activity> APMT_Activity { get; set; }
        public virtual APMT_Company_User APMT_Company_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Process_Role> APMT_Process_Role { get; set; }
    }
}
