//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CP_SPMEntities : DbContext
    {
        public CP_SPMEntities()
            : base("name=CP_SPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APMT_Action> APMT_Action { get; set; }
        public virtual DbSet<APMT_Activity> APMT_Activity { get; set; }
        public virtual DbSet<APMT_Company> APMT_Company { get; set; }
        public virtual DbSet<APMT_Company_User> APMT_Company_User { get; set; }
        public virtual DbSet<APMT_Controller> APMT_Controller { get; set; }
        public virtual DbSet<APMT_Language> APMT_Language { get; set; }
        public virtual DbSet<APMT_Permission> APMT_Permission { get; set; }
        public virtual DbSet<APMT_Process> APMT_Process { get; set; }
        public virtual DbSet<APMT_Process_Role> APMT_Process_Role { get; set; }
        public virtual DbSet<APMT_ProductAdmin> APMT_ProductAdmin { get; set; }
        public virtual DbSet<APMT_Project> APMT_Project { get; set; }
        public virtual DbSet<APMT_User> APMT_User { get; set; }
    }
}
